---
title: 破事一堆
date : 2020-06-21 15:06:30 +0800
categories: [计算机, 笔记]
tags: [计算机, Linux]
---

## 用conda装pytorch装不上

TLNR：最后用pip装的。

用conda装pytorch

```sh
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
```

报错，估计是连不上pytorch和nvidia的网

```
Collecting package metadata (repodata.json): / Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88049b5dd0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /nvidia/noarch/repodata.json.zst

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88049a2690>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /pytorch/noarch/repodata.json.zst

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f87ffe00910>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /pytorch/linux-64/repodata.json.zst

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f880806b0d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /nvidia/linux-64/repodata.json.zst

| Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88048f3ed0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /pytorch/linux-64/repodata.json.zst

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8808002e50>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /pytorch/noarch/repodata.json.zst

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88080037d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /nvidia/noarch/repodata.json.zst

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f87ffd23ad0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /nvidia/linux-64/repodata.json.zst

\ Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88049a1890>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /pytorch/linux-64/repodata.json.zst

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88049a14d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /pytorch/noarch/repodata.json.zst

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88049a3950>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /nvidia/linux-64/repodata.json.zst

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88049a2ad0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /nvidia/noarch/repodata.json.zst

failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/pytorch/linux-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https//conda.anaconda.org/pytorch/linux-64'
```

默认的源

```sh
conda install pytorch torchvision torchaudio pytorch-cuda=12.1
```

找不到pytorch-cuda和torchaudio

```
Channels:
 - defaults
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pytorch-cuda=12.1*
  - torchaudio

Current channels:

  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

到[清华镜像站](https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/win-64/)本地下载对应版本，然后本地安装：

```sh
conda install pytorch-2.3.1-py3.12_cuda12.1_cudnn8_0.tar.bz2
```

`conda list`显示装上了，试试是否可用。

```py
import torch
torch.cuda
```

至少没装完整

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch' has no attribute 'cuda'
```

卸了，加了更多镜像，但还是不行，libcublas安装不上。

```sh
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
conda config --set show_channel_urls yes
```

```
Channels:
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides libcublas >=12.1.0.26,<12.1.3.1 needed by pytorch-cuda-12.1-ha16c6d3_5

Could not solve for environment specs
The following package could not be installed
└─ pytorch-cuda 12.1**  is not installable because it requires
   └─ libcublas >=12.1.0.26,<12.1.3.1 , which does not exist (perhaps a missing channel).
```

应该是恰好没这个版本的libcublas，其他源也下不到，直接去nvidia[那里](https://anaconda.org/nvidia/libcublas/files)下了一个，本地安装

```
Could not solve for environment specs
The following package could not be installed
└─ pytorch-cuda 12.1**  is not installable because it requires
   └─ libcufft >=11.0.2.4,<11.0.2.54 , which does not exist (perhaps a missing channel).
```

好家伙，这一个个的不会都让我本地安装吧。

装了几个之后，发现了安装冲突：

```
Could not solve for environment specs
The following package could not be installed
└─ pytorch-cuda 12.1**  is not installable because it requires
   ├─ cuda-libraries >=12.1,<12.2 , which requires
   │  └─ libcublas 12.1.3.1.* , which can be installed;
   └─ libcublas >=12.1.0.26,<12.1.3.1 , which conflicts with any installable versions previously reported.
```

最后拿pip装了

## 在远程端没python环境

在远程端安装python插件等。

似乎是网的问题，有点装不上，本地安装，下载vsix文件，比如[python](https://marketplace.visualstudio.com/items?itemName=ms-python.python)，点击`Download Extension`，下载好后放到远程端，插件页面右上角三个点，从vsix安装。

```
Unable to install extension 'ms-python.python' as it is not compatible with VS Code '1.83.0'.
```

应该是我vscode版本需要更新了，更新了一下vscode，便携版只要保留`data`文件夹就好了。

结果网好像又好了，能直接在插件商店安装了，所以说不定之前不能安装是因为我vscode版本太旧了。